/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PaginatedExceptionResponse } from '../../models/paginated-exception-response';

export interface AvailabilityControllerListExceptions$Params {
}

export function availabilityControllerListExceptions(http: HttpClient, rootUrl: string, params?: AvailabilityControllerListExceptions$Params, context?: HttpContext): Observable<StrictHttpResponse<PaginatedExceptionResponse>> {
  const rb = new RequestBuilder(rootUrl, availabilityControllerListExceptions.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PaginatedExceptionResponse>;
    })
  );
}

availabilityControllerListExceptions.PATH = '/api/v1/availability/exceptions';
