/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface AvailabilityControllerExportExceptions$Params {
  format: 'csv' | 'xlsx';
}

export function availabilityControllerExportExceptions(http: HttpClient, rootUrl: string, params: AvailabilityControllerExportExceptions$Params, context?: HttpContext): Observable<StrictHttpResponse<any>> {
  const rb = new RequestBuilder(rootUrl, availabilityControllerExportExceptions.PATH, 'get');
  if (params) {
    rb.query('format', params.format, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: 'application/octet-stream', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<any>;
    })
  );
}

availabilityControllerExportExceptions.PATH = '/api/v1/availability/exceptions/export';
