/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AvailabilityExceptionResponse } from '../../models/availability-exception-response';

export interface AvailabilityControllerRestoreException$Params {
  id: string;
}

export function availabilityControllerRestoreException(http: HttpClient, rootUrl: string, params: AvailabilityControllerRestoreException$Params, context?: HttpContext): Observable<StrictHttpResponse<AvailabilityExceptionResponse>> {
  const rb = new RequestBuilder(rootUrl, availabilityControllerRestoreException.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AvailabilityExceptionResponse>;
    })
  );
}

availabilityControllerRestoreException.PATH = '/api/v1/availability/exceptions/{id}/restore';
