/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AvailabilityRuleResponse } from '../../models/availability-rule-response';

export interface AvailabilityControllerGetRules$Params {
}

export function availabilityControllerGetRules(http: HttpClient, rootUrl: string, params?: AvailabilityControllerGetRules$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<AvailabilityRuleResponse>>> {
  const rb = new RequestBuilder(rootUrl, availabilityControllerGetRules.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<AvailabilityRuleResponse>>;
    })
  );
}

availabilityControllerGetRules.PATH = '/api/v1/availability/rules';
