/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AvailabilityRuleResponse } from '../../models/availability-rule-response';

export interface AvailabilityControllerUpsertRule$Params {

/**
 * 0=Sun … 6=Sat
 */
  dayOfWeek: number;
}

export function availabilityControllerUpsertRule(http: HttpClient, rootUrl: string, params: AvailabilityControllerUpsertRule$Params, context?: HttpContext): Observable<StrictHttpResponse<AvailabilityRuleResponse>> {
  const rb = new RequestBuilder(rootUrl, availabilityControllerUpsertRule.PATH, 'put');
  if (params) {
    rb.path('dayOfWeek', params.dayOfWeek, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AvailabilityRuleResponse>;
    })
  );
}

availabilityControllerUpsertRule.PATH = '/api/v1/availability/rules/{dayOfWeek}';
