/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CallResponse } from '../../models/call-response';

export interface RetellCallsControllerFindOne$Params {
  id: string;
}

export function retellCallsControllerFindOne(http: HttpClient, rootUrl: string, params: RetellCallsControllerFindOne$Params, context?: HttpContext): Observable<StrictHttpResponse<CallResponse>> {
  const rb = new RequestBuilder(rootUrl, retellCallsControllerFindOne.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CallResponse>;
    })
  );
}

retellCallsControllerFindOne.PATH = '/api/v1/retell/calls/{id}';
