/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface RetellCallsControllerExport$Params {
  format?: 'csv' | 'xlsx' | 'pdf';
  search?: string;
  callStatus?: string;
  userSentiment?: 'Negative' | 'Positive' | 'Neutral' | 'Unknown';
  status?: 'active' | 'suspended' | 'all';
  withTrashed?: (boolean | 'true' | 'false');
  onlyTrashed?: (boolean | 'true' | 'false');
  start_date?: string;
  end_date?: string;
}

export function retellCallsControllerExport(http: HttpClient, rootUrl: string, params?: RetellCallsControllerExport$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, retellCallsControllerExport.PATH, 'get');
  if (params) {
    rb.query('format', params.format, {});
    rb.query('search', params.search, {});
    rb.query('callStatus', params.callStatus, {});
    rb.query('userSentiment', params.userSentiment, {});
    rb.query('status', params.status, {});
    rb.query('withTrashed', params.withTrashed, {});
    rb.query('onlyTrashed', params.onlyTrashed, {});
    rb.query('start_date', params.start_date, {});
    rb.query('end_date', params.end_date, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

retellCallsControllerExport.PATH = '/api/v1/retell/calls/export';
