/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AppointmentResponse {
  additionalNote: string | null;
  address: string;
  address2: string | null;
  city: string;
  country: string;
  createdAt: string;
  damageDetail: string | null;
  deletedAt: string | null;
  email: string | null;
  firstName: string;
  followUpCalls: any | null;
  followUpDate: string | null;
  id: string;
  inspectionDate: string | null;
  inspectionStatus: 'Confirmed' | 'Completed' | 'Pending' | 'Declined' | 'null';
  inspectionTime: string | null;
  insuranceProperty: boolean;
  intentToClaim: boolean | null;
  isRead: boolean;
  lastName: string;
  latitude: number | null;
  leadSource: 'Website' | 'FacebookAds' | 'Reference' | 'RetellAI' | 'null';
  longitude: number | null;
  message: string | null;
  notes: string | null;
  owner: string | null;
  phone: string;
  registrationDate: string | null;
  smsConsent: boolean;
  state: string;
  statusLead: string | null;
  updatedAt: string;
  zipcode: string;
}
