/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AppointmentListResponse {
  data: Array<{
'id': string;
'firstName': string;
'lastName': string;
'phone': string;
'email': string | null;
'address': string;
'address2': string | null;
'city': string;
'state': string;
'zipcode': string;
'country': string;
'insuranceProperty': boolean;
'message': string | null;
'smsConsent': boolean;
'registrationDate': string | null;
'inspectionDate': string | null;
'inspectionTime': string | null;
'inspectionStatus': 'Confirmed' | 'Completed' | 'Pending' | 'Declined' | 'null';
'statusLead': string | null;
'leadSource': 'Website' | 'FacebookAds' | 'Reference' | 'RetellAI' | 'null';
'followUpCalls': any | null;
'notes': string | null;
'owner': string | null;
'damageDetail': string | null;
'intentToClaim': boolean | null;
'followUpDate': string | null;
'additionalNote': string | null;
'latitude': number | null;
'longitude': number | null;
'isRead': boolean;
'createdAt': string;
'updatedAt': string;
'deletedAt': string | null;
'status': 'active' | 'suspended';
}>;
  limit: number;
  page: number;
  total: number;
}
