/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AvailabilityExceptionResponse {
  createdAt: string;
  date: string;
  deletedAt: string | null;
  id: string;
  isAvailable: boolean;
  reason: string | null;
  status: 'active' | 'suspended';
  updatedAt: string;
}
