/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AvailabilityRuleResponse {
  createdAt: string;
  dayOfWeek: number;
  endTime: string;
  id: string;
  isAvailable: boolean;
  startTime: string;
  updatedAt: string;
}
