/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CallResponse {
  agentId: string | null;
  callId: string;
  callStatus: string | null;
  callSummary: string | null;
  callType: string | null;
  createdAt: string;
  deletedAt: string | null;
  direction: string | null;
  disconnectionReason: string | null;
  durationMs: number | null;
  endedAt: string | null;
  fromNumber: string | null;
  id: string;
  isRead: boolean;
  recordingUrl: string | null;
  startedAt: string | null;
  status: 'active' | 'suspended';
  toNumber: string | null;
  transcript: string | null;
  updatedAt: string;
  userSentiment: string | null;
}
