/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ContactSupportResponse {
  createdAt: string;
  deletedAt: string | null;
  email: string;
  firstName: string;
  id: string;
  isRead: boolean;
  lastName: string;
  message: string;
  phone: string;
  smsConsent: boolean;
  subject: string;
  updatedAt: string;
}
