/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateAppointmentDto {
  additionalNote?: string | null;
  address: string;
  address2?: string | null;
  city: string;
  country: string;
  damageDetail?: string | null;
  email?: string | null;
  firstName: string;
  followUpCalls?: any | null;
  followUpDate?: string | null;
  inspectionDate?: string | null;
  inspectionStatus?: 'Confirmed' | 'Completed' | 'Pending' | 'Declined' | 'null';
  inspectionTime?: string | null;
  insuranceProperty?: boolean;
  intentToClaim?: boolean | null;
  lastName: string;
  latitude?: number | null;
  leadSource?: 'Website' | 'FacebookAds' | 'Reference' | 'RetellAI' | 'null';
  longitude?: number | null;
  message?: string | null;
  notes?: string | null;
  owner?: string | null;
  phone: string;
  registrationDate?: string | null;
  smsConsent?: boolean;
  state: string;
  statusLead?: 'New' | 'Called' | 'Pending' | 'Declined' | 'null';
  zipcode: string;
}
