/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PaginatedExceptionResponse {
  data: Array<{
'id': string;
'date': string;
'isAvailable': boolean;
'reason': string | null;
'status': 'active' | 'suspended';
'createdAt': string;
'updatedAt': string;
'deletedAt': string | null;
}>;
  total: number;
}
