/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { publicAvailabilityControllerGetCalendar } from '../fn/availability-public/public-availability-controller-get-calendar';
import { PublicAvailabilityControllerGetCalendar$Params } from '../fn/availability-public/public-availability-controller-get-calendar';
import { publicAvailabilityControllerGetTimeSlots } from '../fn/availability-public/public-availability-controller-get-time-slots';
import { PublicAvailabilityControllerGetTimeSlots$Params } from '../fn/availability-public/public-availability-controller-get-time-slots';

@Injectable({ providedIn: 'root' })
export class AvailabilityPublicService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `publicAvailabilityControllerGetCalendar()` */
  static readonly PublicAvailabilityControllerGetCalendarPath = '/api/v1/public/availability/calendar';

  /**
   * Get day-level availability for a calendar month.
   *
   * Returns one entry per day in the requested month. Factors in weekly rules (is_available=false days) and date exceptions (holidays / closures).
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `publicAvailabilityControllerGetCalendar()` instead.
   *
   * This method doesn't expect any request body.
   */
  publicAvailabilityControllerGetCalendar$Response(params: PublicAvailabilityControllerGetCalendar$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = publicAvailabilityControllerGetCalendar(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Get day-level availability for a calendar month.
   *
   * Returns one entry per day in the requested month. Factors in weekly rules (is_available=false days) and date exceptions (holidays / closures).
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `publicAvailabilityControllerGetCalendar$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  publicAvailabilityControllerGetCalendar(params: PublicAvailabilityControllerGetCalendar$Params, context?: HttpContext): Promise<void> {
    const resp = this.publicAvailabilityControllerGetCalendar$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `publicAvailabilityControllerGetTimeSlots()` */
  static readonly PublicAvailabilityControllerGetTimeSlotsPath = '/api/v1/public/availability/time-slots';

  /**
   * Get available time slots for a specific date.
   *
   * Returns available 30-minute-step slots for the given date and service duration. Excludes slots blocked by holidays, weekly rules, or existing appointments (±7h buffer).
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `publicAvailabilityControllerGetTimeSlots()` instead.
   *
   * This method doesn't expect any request body.
   */
  publicAvailabilityControllerGetTimeSlots$Response(params: PublicAvailabilityControllerGetTimeSlots$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = publicAvailabilityControllerGetTimeSlots(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Get available time slots for a specific date.
   *
   * Returns available 30-minute-step slots for the given date and service duration. Excludes slots blocked by holidays, weekly rules, or existing appointments (±7h buffer).
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `publicAvailabilityControllerGetTimeSlots$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  publicAvailabilityControllerGetTimeSlots(params: PublicAvailabilityControllerGetTimeSlots$Params, context?: HttpContext): Promise<void> {
    const resp = this.publicAvailabilityControllerGetTimeSlots$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

}
