/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { availabilityControllerCreateException } from '../fn/availability-admin/availability-controller-create-exception';
import { AvailabilityControllerCreateException$Params } from '../fn/availability-admin/availability-controller-create-exception';
import { availabilityControllerDeleteException } from '../fn/availability-admin/availability-controller-delete-exception';
import { AvailabilityControllerDeleteException$Params } from '../fn/availability-admin/availability-controller-delete-exception';
import { availabilityControllerExportExceptions } from '../fn/availability-admin/availability-controller-export-exceptions';
import { AvailabilityControllerExportExceptions$Params } from '../fn/availability-admin/availability-controller-export-exceptions';
import { availabilityControllerGetRules } from '../fn/availability-admin/availability-controller-get-rules';
import { AvailabilityControllerGetRules$Params } from '../fn/availability-admin/availability-controller-get-rules';
import { availabilityControllerListDeletedExceptions } from '../fn/availability-admin/availability-controller-list-deleted-exceptions';
import { AvailabilityControllerListDeletedExceptions$Params } from '../fn/availability-admin/availability-controller-list-deleted-exceptions';
import { availabilityControllerListExceptions } from '../fn/availability-admin/availability-controller-list-exceptions';
import { AvailabilityControllerListExceptions$Params } from '../fn/availability-admin/availability-controller-list-exceptions';
import { availabilityControllerRestoreException } from '../fn/availability-admin/availability-controller-restore-exception';
import { AvailabilityControllerRestoreException$Params } from '../fn/availability-admin/availability-controller-restore-exception';
import { availabilityControllerUpdateException } from '../fn/availability-admin/availability-controller-update-exception';
import { AvailabilityControllerUpdateException$Params } from '../fn/availability-admin/availability-controller-update-exception';
import { availabilityControllerUpsertRule } from '../fn/availability-admin/availability-controller-upsert-rule';
import { AvailabilityControllerUpsertRule$Params } from '../fn/availability-admin/availability-controller-upsert-rule';
import { AvailabilityExceptionResponse } from '../models/availability-exception-response';
import { AvailabilityRuleResponse } from '../models/availability-rule-response';
import { PaginatedExceptionResponse } from '../models/paginated-exception-response';

@Injectable({ providedIn: 'root' })
export class AvailabilityAdminService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `availabilityControllerGetRules()` */
  static readonly AvailabilityControllerGetRulesPath = '/api/v1/availability/rules';

  /**
   * List all 7 weekly availability rules.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `availabilityControllerGetRules()` instead.
   *
   * This method doesn't expect any request body.
   */
  availabilityControllerGetRules$Response(params?: AvailabilityControllerGetRules$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<AvailabilityRuleResponse>>> {
    const obs = availabilityControllerGetRules(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * List all 7 weekly availability rules.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `availabilityControllerGetRules$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  availabilityControllerGetRules(params?: AvailabilityControllerGetRules$Params, context?: HttpContext): Promise<Array<AvailabilityRuleResponse>> {
    const resp = this.availabilityControllerGetRules$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<AvailabilityRuleResponse>>): Array<AvailabilityRuleResponse> => r.body);
  }

  /** Path part for operation `availabilityControllerUpsertRule()` */
  static readonly AvailabilityControllerUpsertRulePath = '/api/v1/availability/rules/{dayOfWeek}';

  /**
   * Create or update a weekly availability rule.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `availabilityControllerUpsertRule()` instead.
   *
   * This method doesn't expect any request body.
   */
  availabilityControllerUpsertRule$Response(params: AvailabilityControllerUpsertRule$Params, context?: HttpContext): Promise<StrictHttpResponse<AvailabilityRuleResponse>> {
    const obs = availabilityControllerUpsertRule(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Create or update a weekly availability rule.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `availabilityControllerUpsertRule$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  availabilityControllerUpsertRule(params: AvailabilityControllerUpsertRule$Params, context?: HttpContext): Promise<AvailabilityRuleResponse> {
    const resp = this.availabilityControllerUpsertRule$Response(params, context);
    return resp.then((r: StrictHttpResponse<AvailabilityRuleResponse>): AvailabilityRuleResponse => r.body);
  }

  /** Path part for operation `availabilityControllerListDeletedExceptions()` */
  static readonly AvailabilityControllerListDeletedExceptionsPath = '/api/v1/availability/exceptions/trash';

  /**
   * List soft-deleted exceptions (trash bin).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `availabilityControllerListDeletedExceptions()` instead.
   *
   * This method doesn't expect any request body.
   */
  availabilityControllerListDeletedExceptions$Response(params?: AvailabilityControllerListDeletedExceptions$Params, context?: HttpContext): Promise<StrictHttpResponse<PaginatedExceptionResponse>> {
    const obs = availabilityControllerListDeletedExceptions(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * List soft-deleted exceptions (trash bin).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `availabilityControllerListDeletedExceptions$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  availabilityControllerListDeletedExceptions(params?: AvailabilityControllerListDeletedExceptions$Params, context?: HttpContext): Promise<PaginatedExceptionResponse> {
    const resp = this.availabilityControllerListDeletedExceptions$Response(params, context);
    return resp.then((r: StrictHttpResponse<PaginatedExceptionResponse>): PaginatedExceptionResponse => r.body);
  }

  /** Path part for operation `availabilityControllerExportExceptions()` */
  static readonly AvailabilityControllerExportExceptionsPath = '/api/v1/availability/exceptions/export';

  /**
   * Export availability exceptions to CSV or XLSX.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `availabilityControllerExportExceptions()` instead.
   *
   * This method doesn't expect any request body.
   */
  availabilityControllerExportExceptions$Response(params: AvailabilityControllerExportExceptions$Params, context?: HttpContext): Promise<StrictHttpResponse<any>> {
    const obs = availabilityControllerExportExceptions(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Export availability exceptions to CSV or XLSX.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `availabilityControllerExportExceptions$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  availabilityControllerExportExceptions(params: AvailabilityControllerExportExceptions$Params, context?: HttpContext): Promise<any> {
    const resp = this.availabilityControllerExportExceptions$Response(params, context);
    return resp.then((r: StrictHttpResponse<any>): any => r.body);
  }

  /** Path part for operation `availabilityControllerListExceptions()` */
  static readonly AvailabilityControllerListExceptionsPath = '/api/v1/availability/exceptions';

  /**
   * List availability exceptions (holidays, closures).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `availabilityControllerListExceptions()` instead.
   *
   * This method doesn't expect any request body.
   */
  availabilityControllerListExceptions$Response(params?: AvailabilityControllerListExceptions$Params, context?: HttpContext): Promise<StrictHttpResponse<PaginatedExceptionResponse>> {
    const obs = availabilityControllerListExceptions(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * List availability exceptions (holidays, closures).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `availabilityControllerListExceptions$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  availabilityControllerListExceptions(params?: AvailabilityControllerListExceptions$Params, context?: HttpContext): Promise<PaginatedExceptionResponse> {
    const resp = this.availabilityControllerListExceptions$Response(params, context);
    return resp.then((r: StrictHttpResponse<PaginatedExceptionResponse>): PaginatedExceptionResponse => r.body);
  }

  /** Path part for operation `availabilityControllerCreateException()` */
  static readonly AvailabilityControllerCreateExceptionPath = '/api/v1/availability/exceptions';

  /**
   * Create a date exception (holiday or closure).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `availabilityControllerCreateException()` instead.
   *
   * This method doesn't expect any request body.
   */
  availabilityControllerCreateException$Response(params?: AvailabilityControllerCreateException$Params, context?: HttpContext): Promise<StrictHttpResponse<AvailabilityExceptionResponse>> {
    const obs = availabilityControllerCreateException(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Create a date exception (holiday or closure).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `availabilityControllerCreateException$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  availabilityControllerCreateException(params?: AvailabilityControllerCreateException$Params, context?: HttpContext): Promise<AvailabilityExceptionResponse> {
    const resp = this.availabilityControllerCreateException$Response(params, context);
    return resp.then((r: StrictHttpResponse<AvailabilityExceptionResponse>): AvailabilityExceptionResponse => r.body);
  }

  /** Path part for operation `availabilityControllerDeleteException()` */
  static readonly AvailabilityControllerDeleteExceptionPath = '/api/v1/availability/exceptions/{id}';

  /**
   * Soft-delete an exception.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `availabilityControllerDeleteException()` instead.
   *
   * This method doesn't expect any request body.
   */
  availabilityControllerDeleteException$Response(params: AvailabilityControllerDeleteException$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = availabilityControllerDeleteException(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Soft-delete an exception.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `availabilityControllerDeleteException$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  availabilityControllerDeleteException(params: AvailabilityControllerDeleteException$Params, context?: HttpContext): Promise<void> {
    const resp = this.availabilityControllerDeleteException$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `availabilityControllerUpdateException()` */
  static readonly AvailabilityControllerUpdateExceptionPath = '/api/v1/availability/exceptions/{id}';

  /**
   * Update an existing exception.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `availabilityControllerUpdateException()` instead.
   *
   * This method doesn't expect any request body.
   */
  availabilityControllerUpdateException$Response(params: AvailabilityControllerUpdateException$Params, context?: HttpContext): Promise<StrictHttpResponse<AvailabilityExceptionResponse>> {
    const obs = availabilityControllerUpdateException(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Update an existing exception.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `availabilityControllerUpdateException$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  availabilityControllerUpdateException(params: AvailabilityControllerUpdateException$Params, context?: HttpContext): Promise<AvailabilityExceptionResponse> {
    const resp = this.availabilityControllerUpdateException$Response(params, context);
    return resp.then((r: StrictHttpResponse<AvailabilityExceptionResponse>): AvailabilityExceptionResponse => r.body);
  }

  /** Path part for operation `availabilityControllerRestoreException()` */
  static readonly AvailabilityControllerRestoreExceptionPath = '/api/v1/availability/exceptions/{id}/restore';

  /**
   * Restore a soft-deleted exception.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `availabilityControllerRestoreException()` instead.
   *
   * This method doesn't expect any request body.
   */
  availabilityControllerRestoreException$Response(params: AvailabilityControllerRestoreException$Params, context?: HttpContext): Promise<StrictHttpResponse<AvailabilityExceptionResponse>> {
    const obs = availabilityControllerRestoreException(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Restore a soft-deleted exception.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `availabilityControllerRestoreException$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  availabilityControllerRestoreException(params: AvailabilityControllerRestoreException$Params, context?: HttpContext): Promise<AvailabilityExceptionResponse> {
    const resp = this.availabilityControllerRestoreException$Response(params, context);
    return resp.then((r: StrictHttpResponse<AvailabilityExceptionResponse>): AvailabilityExceptionResponse => r.body);
  }

}
