/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { CallListResponse } from '../models/call-list-response';
import { CallResponse } from '../models/call-response';
import { retellCallsControllerBulkDelete } from '../fn/retell-calls/retell-calls-controller-bulk-delete';
import { RetellCallsControllerBulkDelete$Params } from '../fn/retell-calls/retell-calls-controller-bulk-delete';
import { retellCallsControllerBulkRestore } from '../fn/retell-calls/retell-calls-controller-bulk-restore';
import { RetellCallsControllerBulkRestore$Params } from '../fn/retell-calls/retell-calls-controller-bulk-restore';
import { retellCallsControllerDelete } from '../fn/retell-calls/retell-calls-controller-delete';
import { RetellCallsControllerDelete$Params } from '../fn/retell-calls/retell-calls-controller-delete';
import { retellCallsControllerExport } from '../fn/retell-calls/retell-calls-controller-export';
import { RetellCallsControllerExport$Params } from '../fn/retell-calls/retell-calls-controller-export';
import { retellCallsControllerFindAll } from '../fn/retell-calls/retell-calls-controller-find-all';
import { RetellCallsControllerFindAll$Params } from '../fn/retell-calls/retell-calls-controller-find-all';
import { retellCallsControllerFindOne } from '../fn/retell-calls/retell-calls-controller-find-one';
import { RetellCallsControllerFindOne$Params } from '../fn/retell-calls/retell-calls-controller-find-one';
import { retellCallsControllerMarkRead } from '../fn/retell-calls/retell-calls-controller-mark-read';
import { RetellCallsControllerMarkRead$Params } from '../fn/retell-calls/retell-calls-controller-mark-read';
import { retellCallsControllerRestore } from '../fn/retell-calls/retell-calls-controller-restore';
import { RetellCallsControllerRestore$Params } from '../fn/retell-calls/retell-calls-controller-restore';
import { retellCallsControllerSync } from '../fn/retell-calls/retell-calls-controller-sync';
import { RetellCallsControllerSync$Params } from '../fn/retell-calls/retell-calls-controller-sync';

@Injectable({ providedIn: 'root' })
export class RetellCallsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `retellCallsControllerFindAll()` */
  static readonly RetellCallsControllerFindAllPath = '/api/v1/retell/calls';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `retellCallsControllerFindAll()` instead.
   *
   * This method doesn't expect any request body.
   */
  retellCallsControllerFindAll$Response(params?: RetellCallsControllerFindAll$Params, context?: HttpContext): Promise<StrictHttpResponse<CallListResponse>> {
    const obs = retellCallsControllerFindAll(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `retellCallsControllerFindAll$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  retellCallsControllerFindAll(params?: RetellCallsControllerFindAll$Params, context?: HttpContext): Promise<CallListResponse> {
    const resp = this.retellCallsControllerFindAll$Response(params, context);
    return resp.then((r: StrictHttpResponse<CallListResponse>): CallListResponse => r.body);
  }

  /** Path part for operation `retellCallsControllerExport()` */
  static readonly RetellCallsControllerExportPath = '/api/v1/retell/calls/export';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `retellCallsControllerExport()` instead.
   *
   * This method doesn't expect any request body.
   */
  retellCallsControllerExport$Response(params?: RetellCallsControllerExport$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = retellCallsControllerExport(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `retellCallsControllerExport$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  retellCallsControllerExport(params?: RetellCallsControllerExport$Params, context?: HttpContext): Promise<void> {
    const resp = this.retellCallsControllerExport$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `retellCallsControllerSync()` */
  static readonly RetellCallsControllerSyncPath = '/api/v1/retell/calls/sync';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `retellCallsControllerSync()` instead.
   *
   * This method doesn't expect any request body.
   */
  retellCallsControllerSync$Response(params?: RetellCallsControllerSync$Params, context?: HttpContext): Promise<StrictHttpResponse<any>> {
    const obs = retellCallsControllerSync(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `retellCallsControllerSync$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  retellCallsControllerSync(params?: RetellCallsControllerSync$Params, context?: HttpContext): Promise<any> {
    const resp = this.retellCallsControllerSync$Response(params, context);
    return resp.then((r: StrictHttpResponse<any>): any => r.body);
  }

  /** Path part for operation `retellCallsControllerBulkDelete()` */
  static readonly RetellCallsControllerBulkDeletePath = '/api/v1/retell/calls/bulk-delete';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `retellCallsControllerBulkDelete()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  retellCallsControllerBulkDelete$Response(params: RetellCallsControllerBulkDelete$Params, context?: HttpContext): Promise<StrictHttpResponse<any>> {
    const obs = retellCallsControllerBulkDelete(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `retellCallsControllerBulkDelete$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  retellCallsControllerBulkDelete(params: RetellCallsControllerBulkDelete$Params, context?: HttpContext): Promise<any> {
    const resp = this.retellCallsControllerBulkDelete$Response(params, context);
    return resp.then((r: StrictHttpResponse<any>): any => r.body);
  }

  /** Path part for operation `retellCallsControllerBulkRestore()` */
  static readonly RetellCallsControllerBulkRestorePath = '/api/v1/retell/calls/bulk-restore';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `retellCallsControllerBulkRestore()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  retellCallsControllerBulkRestore$Response(params: RetellCallsControllerBulkRestore$Params, context?: HttpContext): Promise<StrictHttpResponse<any>> {
    const obs = retellCallsControllerBulkRestore(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `retellCallsControllerBulkRestore$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  retellCallsControllerBulkRestore(params: RetellCallsControllerBulkRestore$Params, context?: HttpContext): Promise<any> {
    const resp = this.retellCallsControllerBulkRestore$Response(params, context);
    return resp.then((r: StrictHttpResponse<any>): any => r.body);
  }

  /** Path part for operation `retellCallsControllerFindOne()` */
  static readonly RetellCallsControllerFindOnePath = '/api/v1/retell/calls/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `retellCallsControllerFindOne()` instead.
   *
   * This method doesn't expect any request body.
   */
  retellCallsControllerFindOne$Response(params: RetellCallsControllerFindOne$Params, context?: HttpContext): Promise<StrictHttpResponse<CallResponse>> {
    const obs = retellCallsControllerFindOne(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `retellCallsControllerFindOne$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  retellCallsControllerFindOne(params: RetellCallsControllerFindOne$Params, context?: HttpContext): Promise<CallResponse> {
    const resp = this.retellCallsControllerFindOne$Response(params, context);
    return resp.then((r: StrictHttpResponse<CallResponse>): CallResponse => r.body);
  }

  /** Path part for operation `retellCallsControllerDelete()` */
  static readonly RetellCallsControllerDeletePath = '/api/v1/retell/calls/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `retellCallsControllerDelete()` instead.
   *
   * This method doesn't expect any request body.
   */
  retellCallsControllerDelete$Response(params: RetellCallsControllerDelete$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = retellCallsControllerDelete(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `retellCallsControllerDelete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  retellCallsControllerDelete(params: RetellCallsControllerDelete$Params, context?: HttpContext): Promise<void> {
    const resp = this.retellCallsControllerDelete$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `retellCallsControllerMarkRead()` */
  static readonly RetellCallsControllerMarkReadPath = '/api/v1/retell/calls/{id}/read';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `retellCallsControllerMarkRead()` instead.
   *
   * This method doesn't expect any request body.
   */
  retellCallsControllerMarkRead$Response(params: RetellCallsControllerMarkRead$Params, context?: HttpContext): Promise<StrictHttpResponse<any>> {
    const obs = retellCallsControllerMarkRead(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `retellCallsControllerMarkRead$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  retellCallsControllerMarkRead(params: RetellCallsControllerMarkRead$Params, context?: HttpContext): Promise<any> {
    const resp = this.retellCallsControllerMarkRead$Response(params, context);
    return resp.then((r: StrictHttpResponse<any>): any => r.body);
  }

  /** Path part for operation `retellCallsControllerRestore()` */
  static readonly RetellCallsControllerRestorePath = '/api/v1/retell/calls/{id}/restore';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `retellCallsControllerRestore()` instead.
   *
   * This method doesn't expect any request body.
   */
  retellCallsControllerRestore$Response(params: RetellCallsControllerRestore$Params, context?: HttpContext): Promise<StrictHttpResponse<any>> {
    const obs = retellCallsControllerRestore(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `retellCallsControllerRestore$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  retellCallsControllerRestore(params: RetellCallsControllerRestore$Params, context?: HttpContext): Promise<any> {
    const resp = this.retellCallsControllerRestore$Response(params, context);
    return resp.then((r: StrictHttpResponse<any>): any => r.body);
  }

}
