/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface PublicAvailabilityControllerGetTimeSlots$Params {

/**
 * Duration in minutes (15–480)
 */
  serviceDuration: number;

/**
 * YYYY-MM-DD in Houston time
 */
  date: string;
}

export function publicAvailabilityControllerGetTimeSlots(http: HttpClient, rootUrl: string, params: PublicAvailabilityControllerGetTimeSlots$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, publicAvailabilityControllerGetTimeSlots.PATH, 'get');
  if (params) {
    rb.query('serviceDuration', params.serviceDuration, {});
    rb.query('date', params.date, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

publicAvailabilityControllerGetTimeSlots.PATH = '/api/v1/public/availability/time-slots';
